# Generated by Django 2.2 on 2019-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablereservation',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='l_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
