# Generated by Django 2.2 on 2019-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190424_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(default='dpeterson@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
