# Generated by Django 2.2 on 2019-04-24 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tablereservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='p_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')]),
        ),
    ]
